config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :accommodations, controller: :properties, only: [:index, :show] do
    post :subscribe, on: :collection
  end


  PagesController.action_methods.each do |action|
    get "/#{action}".dasherize, to: "pages##{action}", as: "#{action}_page"
  end

  post "/contact/thank-you".dasherize, to: "pages#contact_thank_you", as: "post_contact_thank_you_page"
  post "/owners/thank-you".dasherize, to: "pages#owners_thank_you", as: "post_owners_thank_you_page"

  namespace :api do
    resources :units, only: [:index, :show] do
      resources :stays, only: [:get]
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  DATE_FORMAT = '%m/%d/%Y'.freeze

  def index
    search_hash = { area: params[:area], start_date: params[:start_date], end_date: params[:end_date], guests: params[:guests], sort: params[:sort], room: params[:room] }
    searcher = PropertyRetriever.new search_hash
    units = searcher.retrieve
    @units = WillPaginate::Collection.create((params[:page] || 1).to_i, 10, units.count) do |pager|
      pager.replace(units[pager.offset, pager.per_page].to_a)
    end
  end

  def show
    @id                = params[:id]
    @unit              = UnitRepository.get(@id)
    @property_title    = @unit.name
    @property_subtitle = @unit.address[:street]
    @amenities         = @unit.available_amenities
    @guests            = params[:guests] || 1
    @guest_amount_list = (1..@unit.occupancy).map { |v| v }
    @start_date        = !params[:start_date].blank? ? params[:start_date] : Date.today.strftime(DATE_FORMAT)
    @end_date          = !params[:end_date].blank? ? params[:end_date] : (Date.today + 7).strftime(DATE_FORMAT)
    @random_units      = UnitRepository.random_units(limit: 3, except: [@id])

    lookup_rates if [:start_date, :end_date, :guests].all? { |k| params.key?(k) && !params[k].blank? }
    get_images
  end

  def subscribe
    AppMailer.subscribe(params[:subscribe][:email]).deliver_now
    redirect_to root_path
  end

  private

  def lookup_rates
    @lookup         = true
    @available      = true
    start_date      = Date.strptime(@start_date, DATE_FORMAT)
    end_date        = Date.strptime(@end_date, DATE_FORMAT)
    @length_of_stay = end_date.mjd - start_date.mjd
    @guests         = @guests == PropertyRetriever::ANY ? 1 : @guests

    @rates = Stay.lookup(@id,
                        start_date: start_date,
                        end_date: end_date,
                        guests: @guests)

    @nightly_rate      = '%.2f' % (@rates.base_amount / @length_of_stay)
    @base_amount       = '%.2f' % @rates.base_amount
    @tax_amount        = '%.2f' % @rates.taxes[0].amount
    @fees              = @rates.fees
    @total_amount      = '%.2f' % @rates.total_amount
  rescue Stay::Unavailable
    @available = false
  end

  def get_images
    @videos = @unit.videos
    @standard_images = @unit.standard_images
    @large_images = @unit.large_images
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_rate_panel.html.slim
aside.request-booking.md-one-third
  - if @lookup && @available
    header.booking-header
      h2
        | $
        = '%.0f' % @nightly_rate
        span.term
          | Per Night
    = form_tag("/accommodations/#{@id}", {method: 'get', class: 'gw no-gutter booking-details'}) do
      table
        tr.date-select
          td.g.sm-three-eighths
            label[for="start_date"]
              | Arrive
            = text_field_tag "start_date", @start_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy'
          td.g.sm-three-eighths
            label[for="end_date"]
              | Depart
            = text_field_tag "end_date", @end_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy'
          td.g.sm-two-eighths
            label[for="guests"]
              | Guests
            .select-style
              = select_tag "guests", options_for_select(@guest_amount_list, @guests)
        tr.full-width-container
          td
            input.btn.no-min-width[type="submit" value="Search Again"]
        tr.details.first
          td.g.two-thirds
            | $
            =  '%.0f' % @nightly_rate
            |  x 
            = @length_of_stay
            |  nights
          td.g.one-third
            | $
            = @base_amount
        tr.details
          td.g.two-thirds
            | Tax
          td.g.one-third
            | $
            = @tax_amount
        - @fees.each do |fee|
          tr.details
            td.g.two-thirds
              = fee.name
            td.g.one-third
              | $
              = '%.2f' % fee.amount
        tr.details
          td.g.two-thirds.highlight
            | Total
          td.g.one-third.highlight
            | $
            = '%.2f' % @total_amount
        tr.details
          td.g.two-thirds
            a[href="/trip-cancellation-insurance" target="_blank"]
              | Optional Trip Cancellation Insurance
          td.g.one-third
            | $
            = '%.2f' % ((@base_amount.to_f * 1.12) * 0.065)
        tr.details
          td.g.two-thirds.highlight
            | Total w/ Insurance
          td.g.one-third.highlight
            | $
            = '%.2f' % (((@base_amount.to_f * 1.12) * 0.065) + @total_amount.to_f)
        tr.full-width-container
          td
            |  <a href="http://bookings.oceano-rentals.com/Booking/RateDetails/
            = booking_id
            | ?arrive=
            = @start_date
            | &depart=
            = @end_date
            | &adults=
            = @guests
            | " class="btn request-booking-link">Request Booking
        tr.full-width-container
          td
            span.note
              | The total above is an estimate and includes rent, taxes, and additional fees.
  - elsif @lookup && !@available
    header.booking-header
      h2
        | Availability and Rate
    = form_tag("/accommodations/#{@id}", {method: 'get', class: 'gw no-gutter booking-details'}) do
      table
        tr.date-select
          td.g.sm-three-eighths
            label[for="start_date"]
              | Arrive
            = text_field_tag "start_date", @start_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy'
          td.g.sm-three-eighths
            label[for="end_date"]
              | Depart
            = text_field_tag "end_date", @end_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy'
          td.g.sm-two-eighths
            label[for="guests"]
              | Guests
            .select-style
              = select_tag "guests", options_for_select(@guest_amount_list, @guests)
        tr.full-width-container
          td.g
            | This property is unavailable for the chosen dates.
        tr.full-width-container
          td
            input.btn.no-min-width[type="submit" value="Check Availability"]
  - else
    header.booking-header
      h2
        | Availability and Rate
    = form_tag("/accommodations/#{@id}", { method: 'get', class: 'gw no-gutter booking-details' }) do
      table
        tr.date-select
          td.g.sm-three-eighths
            label[for="start_date"]
              | Arrive
            = text_field_tag "start_date", @start_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy'
          td.g.sm-three-eighths
            label[for="end_date"]
              | Depart
            = text_field_tag "end_date", @end_date, class: 'no-borders datepicker', placeholder: 'mm/dd/yyyy'
          td.g.sm-two-eighths
            label[for="guests"]
              | Guests
            .select-style
              = select_tag "guests", options_for_select(@guest_amount_list, @guests)
        tr.full-width-container
          td.g
            | Check availablilty to view rates and fees.
        tr.full-width-container
          td
            input.btn.no-min-width[type="submit" value="Check Availability"]

app/views/properties/_search_form.html.slim
form#search_filter.search-form data-toggle="validator" action="#{accommodations_path}" method="get"
  .form-input.location-select
    / i.fa.fa-bed aria-hidden="true"
    select name="rooms" required=""
      = options_for_select(areas, @area)
  .form-input.date-input
    input#start_date.datepicker.arrival-date autocomplete="off" name="start_date" placeholder=("CHECK IN") readonly="readonly" type="text" required="" /
    / i.fa.fa-calendar aria-hidden="true"
  .form-input.date-input
    input#end_date.datepicker.depart-date autocomplete="off" name="end_date" placeholder=("CHECK OUT") readonly="readonly" type="text" required="" /
    / i.fa.fa-calendar aria-hidden="true"
  .form-input.guests-select
    / i.fa.fa-user aria-hidden="true"
    select.guests-select name="guests"
      = options_for_select(guests)
  .form-input.submit
    button.btn.search-btn.sandcastle-text-capitalization type="submit" Search

app/views/properties/index.html.slim
- content_for :hero_title, "Reserve"
- content_for :lede, "Search for a rental at Rocky Point"
section.padded-top.scallop-top.beige-bg
  .layout-container
    .property-search
      = render partial: 'properties/search_form', locals: { area: params[:area], start_date: params[:start_date], end_date: params[:end_date], sort: retrieve_sort }
  .layout-container
    ul.properties-list.gw.small-gutter
      - @units.each do |unit|
        li.property.g.sm-one-half.md-one-whole
          a href="#{generate_property_url unit.code}"
            img.property-thumb src="#{unit.standard_images[0][:url]}"
          .details
            .gw.small-gutter
              .g.md-three-eighths
                h2
                  a href="#{generate_property_url unit.code}" = unit.name
                p.location
                  |#{unit.address.street}
                  br
                  |#{unit.address.city}, #{unit.address.country}
              .g.md-four-eighths
                ul.offerings
                  li
                    i.icon.icon-bath
                    span.detail #{unit.bathrooms} bath
                  li
                    i.icon.icon-bed
                    span.detail #{unit.bedrooms} beds
                  li
                    i.icon.icon-guests
                    span.detail #{unit.occupancy} guests
              .g.md-one-eighth
                span.price
                span.type #{unit.type}
    .pagination.pagination-centered
      = will_paginate @units, previous_label: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.3 32.6"><polygon points="16.3,32.6 0,16.3 16.3,0"/></svg>',
                                         next_label: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.3 32.6"><polygon points="0,0 16.3,16.3 0,32.6"/></svg>'

app/views/properties/show.html.slim
script[type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false"]
- content_for :hero_title, @property_title.html_safe
- content_for :lede, @property_subtitle.html_safe
section.scallop-top
  .layout-container
    .md-two-thirds
      ul.offerings
        li
          i.icon.icon-bath
          span.detail #{@unit.bathrooms} Bath
        li
          i.icon.icon-bed
          span.detail #{@unit.bedrooms} Beds
        li
          i.icon.icon-guests
          span.detail #{@unit.occupancy} Guests
        li
          i.icon.icon-apartment
          span.detail #{@unit.type.capitalize}
section.padded-top.padded-bottom.beige-bg
  .layout-container
    = render 'rate_panel'
    .property-details.md-two-thirds
      #image-lightbox.image-grouping
        .row
          - if @large_images.count > 0
            article.one-whole.md-two-thirds.tile
              a.fancybox.contain rel="image-gallery" href="#{@large_images[0][:url]}" title="#{@large_images[0][:title]}" style="background-image: url('#{@standard_images[0][:url]}');"
          - if @large_images.count > 1
              a.fancybox.contain rel="image-gallery" href="#{@large_images[1][:url]}" title="#{@large_images[1][:title]}" style="background-image: url('#{@standard_images[1][:url]}');"
        .row
          - if @large_images.count > 2
            article.one-whole.md-one-third.tile
              a.fancybox.contain rel="image-gallery" href="#{@large_images[2][:url]}" title="#{@large_images[2][:title]}" style="background-image: url('#{@standard_images[2][:url]}');"
          - if @large_images.count > 3
            article.one-whole.md-one-third.tile
              a.fancybox.contain rel="image-gallery" href="#{@large_images[3][:url]}" title="#{@large_images[3][:title]}" style="background-image: url('#{@standard_images[3][:url]}');"
          - (5..@standard_images.count).each do |index|
              a.fancybox.hidden rel="image-gallery" href="#{@large_images[index - 1][:url]}" title="#{@large_images[index - 1][:title]}" style="background-image: url('#{@standard_images[index -1][:url]}');"
          article.one-whole.md-one-third.tile
            a.contain.black.placehold-all-images.open-lightbox href="#"
              .over
                h2 See All #{@standard_images.count} Photos
      .gw
        .g
          - unless @videos.empty? || @videos[0][:formats][:url].empty?
            p
              a.fancybox-media.btn.video-tour-btn title="Video Tour" href="#{@videos[0][:formats][:url]}" target="_blank" View a video tour
      .gw
        .g.md-one-fourth
          h2.heading-two
            | Description
        .g.md-three-fourths
          p
            = @unit.descriptions[:text][0][:description]
      hr
      .gw
        .g.md-one-fourth
          h2.heading-two Property Details
        .g.md-three-fourths
          ul.gw.no-gutter.no-padding
            li.g.md-one-half.padded-right
              p
                b Property Type: #{@unit.type.capitalize}
            li.g.md-one-half.padded-right
              p
                b Bedrooms: #{@unit.bedrooms}
            li.g.md-one-half.padded-right
              p
                b Bathrooms: #{@unit.bathrooms}
            li.g.md-one-half.padded-right
              p
                b Floors: #{@unit.num_floors}
            li.g.md-one-half.padded-right
              p
                b Occupancy: #{@unit.occupancy}
      hr
      .gw
        .g.md-one-fourth
          h2.heading-two Amenities
        .g.md-three-fourths
          ul.gw.no-gutter.no-padding
            - @amenities.each do |amenity|
              li.g.md-one-half.padded-right
                p = amenity.to_s.titleize
- @unit.reviews.sample(3).compact.tap do |reviews|
  - break if reviews.empty?
  section.padded-top.padded-bottom
    .layout-container
      .md-two-thirds
        h2.heading-two.bottom-spacing-large
          | Testimonies
        ul.testimonials.testimonials-paginated.normal.gw.large-gutter
          - reviews.each do |review|
            li.g.sm-one-whole
              blockquote
                p.persons-words
                  | “ #{review[:comment].html_safe}
                - unless review[:city].empty? || review[:state].empty?
                  span.persons-name #{review[:city]}, #{review[:state]}
  #map-container
    #map-canvas data-lat="#{@unit.position[:latitude]}" data-lon="#{@unit.position[:longitude]}"
  section.padded-top.padded-bottom.related-places
    .layout-container
      h2.heading-two.bottom-spacing-large Other Places
      ul.gw.large-gutter.no-padding
        - @random_units.each do |unit|
          li.g.md-one-third
            a href="#{accommodation_url(unit.code)}"
              img src="#{unit.standard_images[0][:url]}"
            h2.top-spacing = unit.name
            p
              = ellipsis(unit.long_description, length: 50)