config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :accommodations, controller: :properties, only: [:index, :show] do
    post :subscribe, on: :collection
  end


  PagesController.action_methods.each do |action|
    get "/#{action}".dasherize, to: "pages##{action}", as: "#{action}_page"
  end

  post "/contact/thank-you".dasherize, to: "pages#contact_thank_you", as: "post_contact_thank_you_page"
  post "/owners/thank-you".dasherize, to: "pages#owners_thank_you", as: "post_owners_thank_you_page"

  namespace :api do
    resources :units, only: [:index, :show] do
      resources :stays, only: [:get]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    units_data = RedisClient.get 'temp:units:values'
    units = JSON.parse(units_data)
    @random_units = []
    units.each do |unit|
      @random_units << unit if unit['type'] == 'condominium' || unit['type'] == 'townhouse'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_slider.html.slim
section.featured-rooms-slider-section
  .layout-container.margin-0 style="padding:0px;" 
    .md-one-whole.sm-one-whole.lg-one-whole.left-padding-by-5.slider5
      - units.sample(6).each do |unit|
        .md-one-whole.sm-one-whole
          .md-six-twelfths.sm-six-twelfths.lg-six-twelfths.float-left
            .md-one-whole.sm-one-whole.call-now-bg
              span.call-now-text Call Now
              .phone-number-text
                a.font-color-white href=("tel:(888) 328-8491")  (888) 328-8491
            .room-details-main-div
              .hot-offer HOT OFFER
              .room-name-text
                = truncate(unit['name'], :length => 25)
              .rating-icon-div
                i.fa.fa-star
                i.fa.fa-star
                i.fa.fa-star
                i.fa.fa-star
                i.fa.fa-star-half-o
              .room-details
                = unit['descriptions']['text'][2]['description']
              a href="#{accommodation_path unit['code']}"
                button.view-offer-btn type="submit" View Offer
              i.fa.fa-arrow-right  style=("position: absolute; margin-left: -30px; margin-top: 17px; color: white;") 
          .md-six-twelfths.sm-six-twelfths.lg-six-twelfths.float-left.slider-image
            .md-one-whole.sm-one-whole.call-now-bg  style=("border-radius: 0 0 30px 0;color:white;text-transform:lowercase;position: absolute;width: 125px;padding:30px 0 0 30px;background:#39bdfb;") 
              span style=("font-size: 4vmin;font-weight: bold;") 
                - if !unit[:price].blank?
                  = unit[:price]
                - if !unit['stay_ranges'].blank?
                  = unit['stay_ranges'].first['price']
              br per night
            img alt="" height="420" src="#{unit['descriptions']['images'][0]['formats'][2]['url']}"
            .room-icon-layer
              .room-amenity
                .room-bath
                  i.icon.icon-bath.white
                  .text
                    = unit['bathrooms']
                .room-bed
                  i.icon.icon-bed.white
                  .text
                    = unit['bedrooms']
                .room-users
                  i.icon.icon-guests.white
                  .text
                    = unit['occupancy']
                .room-building
                  i.icon.icon-apartment.white
                  .text
                    - if unit['type'] == 'condominium'
                      | Condo
                    - else
                      | Townhouse
          .md-two-twelfths.sm-two-twelfths.lg-two-twelfths.float-left.last-child-div
            img alt="" src="#{image_path 'st-jude-on-the-little.jpg'}"

app/views/home/index.html.slim
- content_for :header_class, 'full-background homepage-header-content'
- content_for :hero_class, 'no-bg'
- content_for :hero_size, 'hero-medium'
- content_for :hero_title, "FIND YOUR PERFECT GETAWAY".html_safe
section.main-content.z-index-1
  .layout-container.layout-centered style="padding:0px;" 
    .property-search.welcome-text-align-for-smaller
      == render partial: 'properties/search_form', locals: { area: @area, start_date: @start_date, end_date: @end_date, sort: @sort }
.section-divider.main-content-sectio-devider
  img src="#{image_path 'divider.png'}"
.main-heading-div.main-content-sectio-devider-feature
  img src="#{image_path 'featured-rooms-text.png'}"

= render partial: 'slider', locals: { units: @random_units }
/! testimonial section
.section-divider
  img src="#{image_path 'divider.png'}"
section.testimonial-bg-image
  .testimonial-main-div
    .md-one-whole.sm-one-whole.lg-one-whole.left-padding-by-5.testimonial-slider
      .user-image
        = image_tag "testimonial_user_image.png", :class => "center-image-align"
        div
          p.text-align-center.margin-top-0.testimonial-comment Rental was clean and well furnished.  We were just where we wanted to be...right on the beach.
          p.text-align-center.testimonial-user-name Janice Lucero
          .testimonial-user-rating
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star-half-o
          p.text-align-center.testimonial-comment COURTYARD 1
      div
        .user-image
          = image_tag "testimonial_user_image.png", :class => "center-image-align"
        div
          p.text-align-center.margin-top-0.testimonial-comment I was very pleased with our stay at Hacienda Del Mar. It's very close to the beach. Less then a two minute walk. The AC units are very cold. Turn them on and is 15 mins the rooms are cool. The property is very private so you can relax outside and take in the sea breeze. I read other reviews and I'm glad I choose to experience it for myself. I would definitely stay here again in the future.
          p.text-align-center.testimonial-user-name Leo Madrid
          .testimonial-user-rating
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star-half-o
          p.text-align-center.testimonial-comment COURTYARD 1
      div
        = image_tag "testimonial_user_image.png", :class => "center-image-align"
        div
          p.text-align-center.margin-top-0.testimonial-comment Buena estancia, la casa estaba muy limpia y sin ningún problema de servicio, esta diseñada para grupos individuales, tiene múltiples cocinas y areas.
          p.text-align-center.testimonial-user-name Raul Villalva
          .testimonial-user-rating
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star
            i.fa.fa-star-half-o
          p.text-align-center.testimonial-comment COURTYARD 1
.section-divider
  img src="#{image_path 'divider.png'}"
.main-heading-div
  img src="#{image_path 'featured-attraction-text.png'}"
/! Featured Attractions
section.padding-bottom-2.padding-top-1
  .feature-atrraction-sliders
    .md-one-whole.sm-one-whole.lg-one-whole.left-padding-by-5.featured-attraction-slider
      .venues
        img.outfocus-images src="#{image_path 'IMG_1900.jpg'}"
      .venues
        img.outfocus-images src="#{image_path 'cholla-bay.jpg'}"
        .image-caption CHOLLA BAY
      .venues
        img.outfocus-images src="#{image_path 'ecofun-rentals.jpg'}"
        .image-caption ECOFUN RENTALS
      .venues
        img.outfocus-images src="#{image_path 'playa-bonita.gif'}"
        .image-caption PLAYA BONITA BEACH
      .venues
        img.outfocus-images src="#{image_path 'street-view.jpg'}"
.section-divider
  img src="#{image_path 'divider.png'}"
section.get-some-deal
  .subscribe-email-div
    = render partial: 'shared/subscription'